[package]
name = "vq9o/knightremotes"
version = "2.0.2"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
class = "raphtalia/class@1.0.2"
sift = "csqrl/sift@0.0.11"